export const PRODUCTS = [
  {
    id: '1',
    name: 'Elegant Ceramic Vase',
    description: 'A beautifully handcrafted ceramic vase, perfect for adding a touch of elegance to any room. Its minimalist design and smooth finish make it a versatile piece for various decor styles.',
    price: 89.99,
    imageUrl: 'https://m.media-amazon.com/images/I/61NOoIf7+cL._AC_.jpg',
  },
  {
    id: '2',
    name: 'Luxurious Silk Scarf',
    description: 'Experience the soft embrace of this luxurious silk scarf. Adorned with a subtle, intricate pattern, it’s an ideal accessory for both formal and casual outfits.',
    price: 59.50,
    imageUrl: 'https://i.ebayimg.com/images/g/HmIAAOSwgDhjk9Zw/s-l960.jpg',
  },
  {
    id: '3',
    name: 'Artisan Leather Wallet',
    description: 'Crafted from premium full-grain leather, this artisan wallet combines durability with timeless style. Featuring multiple card slots and a spacious bill compartment, it’s both practical and sophisticated.',
    price: 120.00,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0298/0353/products/FG01692024_large.jpg?v=1506220278',
  },
  {
    id: '4',
    name: 'Modernist Desk Lamp',
    description: 'Illuminate your workspace with this sleek modernist desk lamp. Its adjustable arm and warm LED light provide optimal lighting for productivity and comfort.',
    price: 149.00,
    imageUrl: 'https://a.1stdibscdn.com/archivesE/1stdibs/030414/StripeCC_DM/7/X.jpg?disable=upscale&auto=webp&quality=60&width=1318',
  },
  {
    id: '5',
    name: 'Hand-Woven Wool Rug',
    description: 'Bring warmth and texture to your living space with this exquisite hand-woven wool rug. Its geometric pattern and natural fibers create a cozy yet chic ambiance.',
    price: 299.00,
    imageUrl: 'https://img0.etsystatic.com/127/0/11422428/il_fullxfull.1041599172_6h8t.jpg',
  },
  {
    id: '6',
    name: 'Vintage Espresso Machine',
    description: 'Indulge in the rich aroma of freshly brewed coffee with this vintage-inspired espresso machine. A perfect blend of classic aesthetics and modern functionality.',
    price: 380.00,
    imageUrl: 'https://tse4.mm.bing.net/th/id/OIP.G5AWqlq2CiwDD7PcOLaqfwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: '7',
    name: 'Organic Cotton Bedding Set',
    description: 'Drift into serene slumber with our organic cotton bedding set. Made from 100% natural fibers, it offers unparalleled softness and breathability for a restful night.',
    price: 195.00,
    imageUrl: 'https://tse1.mm.bing.net/th/id/OIP.hDbPFheJrBmS-mXFl6Y56wHaFO?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: '8',
    name: 'Minimalist Wall Clock',
    description: 'A statement piece for any minimalist interior, this wall clock features a clean design with precise quartz movement. Time-telling has never been this stylish.',
    price: 75.00,
    imageUrl: 'https://img.freepik.com/premium-photo/modern-minimalist-wall-clock_777078-158887.jpg',
  },
  {
    id: '9',
    name: 'Sculptural Bookshelf',
    description: 'Organize your literary collection with this uniquely designed sculptural bookshelf. Its asymmetrical compartments provide both storage and an artistic display.',
    price: 450.00,
    imageUrl: 'https://thumbs.dreamstime.com/b/sculptural-bookshelf-made-polished-wood-set-against-minimalist-living-room-backdrop-319109000.jpg',
  },
  {
    id: '10',
    name: 'Smart Home Speaker',
    description: 'Immerse yourself in crystal-clear audio and intelligent assistance with this smart home speaker. Seamlessly integrates with your devices and responds to voice commands.',
    price: 220.00,
    imageUrl: 'https://tse3.mm.bing.net/th/id/OIP.VICK2QgaJmPbhIga7l10YQHaEJ?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
];